# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerInstaller@0
      enabled: false
      inputs:
        dockerVersion: '20.10.7'
    - task: Bash@3
      enabled: false
      inputs:
        targetType: 'inline'
        script: 'sudo systemctl start docker'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'beta-repo'
        repository: 'miningcore'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'
        tags: |
          latest
          $(tag)
